feat: implement email domain validation with unit tests (#143)
* feat: implement email domain validation with unit tests

* refactor: refactor schema validation and separate validation directives from controllers

* test: add tests for EmailValidator for cases where isVerifiable is true

* chore: run prettier write

* refactor: Use spyOn mockImplementation instead of manual __mocks__

* fix: hoist directives

* style: disable toggle when email isVerifiable is false and update tooltip for email domain fields

* feat: use user's email domain and @agency.gov.sg as allowed email domains placeholder and migrate email validation tests

* fix: update label for email domain textarea field, add horizontal line below the field and prevent error when textarea value is empty (cannot call .split on empty string)

* fix: set hasAllowedEmailDomains to false when isVerifiable is false pre-save

* fix: fix email schema pre-save hook and add directive to intercept isVerifiable save

* feat: trigger toast when isVerifiable is switched off

* fix: hide textarea for email domains if switch is off

* fix: resolve error TS2339: Property 'hasAllowedEmailDomains' does not exist on type 'IEmailFieldSchema'.

* fix: remove unneeded pre-save interceptor for hasAllowedEmailDomains

* fix: fix directive logic and refactor label names so that they follow the mockups

* fix: update toggle name in test as well

* refactor: update line CSS class name, use import from instead of import require and add a warning to prevent changes to onclick=""

* fix: fix CSS selector clash and handle Auth.getUser() if it's null

* fix: fix error TS2320: Interface 'IEmailFieldSchema' cannot simultaneously extend types 'IEmailField' and 'IFieldSchema'.

* feat: implement dynamic tooltip text depending on emptiness check for allowedEmailDomainsFromText

* refactor: rename vm.tooltipText to vm.tooltipHtml for more clarity